### ISSUE TITLE
Downloading better-sqlite3

### ISSUE THREAD

**Issue by cgoldman123** [comp426-2022-spring/a04#14]
Hey guys,

I saw the old issue for downloading better-sqlite3 but it was closed so I figure I'd open a new one. 

I've followed all the steps in #8 but had no luck.

I'm using a Mac.
node version v16.14.2
python version 3.8.3

Here's a snippet of my error code:

npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: 426: command not found
npm ERR! node:internal/fs/utils:344
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: ENOENT: no such file or directory, copyfile 

Please let me know if you have any suggestions!

**Comment by ZheyuHuang** [comment]
It's a weird bug. I had the same issue, and I went back to check my directory path. Seems like it doesn't allow any spaces in the path. In my case, I changed my folder from "COMP 426" to "COMP-426", and it then worked.

**Comment by cgoldman123** [comment]
Thanks! That helped @ZheyuHuang
