### ISSUE TITLE
Struggling to follow Directions

### ISSUE THREAD

**Issue by nholmes26** [comp426-2022-spring/a04#2]
I am creating this issue so that I can attend office hours and ask some basic questions about getting started. I got to the part where it talks about creating endpoints and realized that I don't have a great understanding of what I am programming here, so I want to make sure what I have so far is on the right track.

**Comment by samrshi** [comment]
resolved in office hours: create database in its own js file and export it. import that into your server.js file and do the database operations in your endpoint/middleware functions
