### ISSUE TITLE
Middleware Function

### ISSUE THREAD

**Issue by andymking** [comp426-2022-spring/a04#3]
For a04, the requirements state:
Write a middleware function that writes the logdata object variables into the accesslog table in log.db.

Can this be done using one middleware function that is used by all endpoints in our API to log access data of users of our application, or should all of our endpoints use their own middleware function in the body of each endpoint.

I hope that wording makes sense, and I can come into office hours if not.

Andy

**Comment by andymking** [comment]
I figured it out im dumb thank you

**Comment by jdmar3** [comment]
Not dumb at all!

What was your solution?
