### ISSUE TITLE
sqlite error when creating database

### ISSUE THREAD

**Issue by mziade** [comp426-2022-spring/a04#6]
![Screen Shot 2022-04-08 at 1 58 29 PM](https://user-images.githubusercontent.com/59807096/162495854-aa65f6fe-9448-4e8d-a7a8-e7c2404587bb.png)

I am getting this error whenever I try to create the database, not sure how to go about solving it.

**Comment by taylorrk** [comment]
I am also having this issue!

**Comment by mziade** [comment]
solved with fixing the sql syntax! @taylorrk I think the notes from w08 have been updated so go check out that code.
